// Auto-generated training history from ML models
// Generated by export_to_dashboard.py

export interface TrainingHistory {
  loss: number[];
  val_loss?: number[];
}

export const trainingHistory: Record<string, Record<string, TrainingHistory>> = {
  "v1": {},
  "v2": {},
  "v3": {}
};
